num_cluster: 5
d_model: 256
ffn_dim: 512
attn_layers: 4
fc_dim: [128]
dropout: 0.1
num_classes: 3
epochs: [100,100,100]
eval_epoch: [1,1,1]
batch_size: [32,128,32]
eval_batch_size: [32,32,32]
pred_mask_rate: 0
weighted_sampling: False
class_weight_type: "none"
class_weight_scale: 1
alpha: 1
beta: 1
lr: [2e-5,1e-4]
actor_lr: 2e-5
critic_lr: 2e-5
embedding_lr: 2e-5